baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "anatole"
summarylength =10 
pygmentsCodeFences = true
pygmentsUseClasses = true
disqusShortname = "saravanas-blog"
[params]
	title = "Saravana's Blog"
	author = "Saravanan"
	description = "A curated version of my thoughts"
	profilePicture = "images/dp.jpeg"
	contactFormAction = "https://formspree.io/f/mleyoopy"
	displayMode = "dark"
	contentratio = 0.7
	customCss = ["css/syntax.css"]
	listDateFormat = "Jan 2"
	singleDateFormat = "Mon, Jan 2, 2006"
	indexDateFormat = "Mon, Jan 2, 2006"
	readMore = true
	thumnail_height = 200
[[params.socialIcons]]
	icon = "fab fa-linkedin"
	title = "Linkedin"
	url = "https://www.linkedin.com/in/saravanan-m-100728186/"

[[params.socialIcons]]
	icon = "fab fa-github"
	title = "Github"
	url = "https://github.com/imsaravana369"

[[params.socialIcons]]
   icon = "fab fa-medium"
   title = "Medium"
   url  = "https://medium.com/@imsaravananm"
[menu]

  [[menu.main]]
  name = "Posts"
  identifier = "Posts"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  
  [[menu.main]] 
  name = "Contact"
  weight = 600
  identifier = "contact"
  url = "/contact/"


[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"
[params.umami]
serverURL = "umami-production-5ca8.up.railway.app"
id = "818a9100-58b7-43f0-a9b6-c65df2e55f3c"
trackerScriptName = "script.js"

